apiVersion: v1
kind: PersistentVolume
metadata:
  name: primary-postgresql-pv
spec:
  capacity:
    storage: {{ .Values.postgresql.primary.volumeSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/primary

