apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primary-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.volumeSize }}

