apiVersion: v1
kind: Service
metadata:
  name: primary-postgresql
spec:
  type: {{ .Values.postgresql.primary.serviceType }}
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: primary-postgresql

