apiVersion: apps/v1
kind: Deployment
metadata:
  name: standalone-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standalone-postgresql
  template:
    metadata:
      labels:
        app: standalone-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:17
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
            - name: PGDATA
              value: "/var/lib/postgresql/data"
            - name: PRIMARY_HOST
              value: "primary-postgresql.default.svc.cluster.local" 
            - name: PGHOST
              value: "/run/postgresql"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    if [ ! -f /var/lib/postgresql/data/standby.signal ]; then
                      echo "Replication setup started";
                      until pg_basebackup -h ${PRIMARY_HOST} -D /var/lib/postgresql/data -Fp -Xs -P -R -W; do
                        echo "Waiting for primary to be ready...";
                        sleep 10;
                      done
                      echo "Replication setup complete";
                    else
                      echo "Standby already initialized. Skipping pg_basebackup.";
                    fi
      initContainers:
        - name: pg-basebackup
          image: postgres:17
          command:
            - /bin/bash
            - -c
            - |
              echo "Cleaning up data directory before standalonetion...";
              rm -rf /var/lib/postgresql/data/*;
              echo "Starting pg_basebackup from primary...";
              until pg_basebackup -U postgres -D /var/lib/postgresql/data -h primary-postgresql.default.svc.cluster.local --checkpoint=fast; do
                echo "Retrying pg_basebackup in 10 seconds...";
                sleep 10;
              done
              echo "pg_basebackup complete";
              touch /var/lib/postgresql/data/standby.signal;
              echo "primary_conninfo = 'host=primary-postgresql.default.svc.cluster.local user=postgres password=postgres'" >> /var/lib/postgresql/data/postgresql.auto.conf;
          env:
            - name: PGPASSWORD
              value: "postgres"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: standalone-postgresql-pvc

