apiVersion: v1
kind: PersistentVolume
metadata:
  name: replica-postgresql-pv
spec:
  capacity:
    storage: {{ .Values.postgresql.replica.volumeSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/replica

