apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replica-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.replica.volumeSize }}

